### ISSUE TITLE
Erroneous consumption value 4294967.295 (electricity)

### ISSUE THREAD

**Issue by matroderick** [n3rgy/data#11]
Occasionally, SMEST1 electricity meters have been seen to report an anomalously high consumption value, reporting 4294967.295 or 2147483.647 within single 30min periods. This is a result of the meter failing to capture the consumption value correctly and reporting this value an an error code. This is a "feature" of the SMETS specification, the specification uses abnormally high values within the consumption field as an error code (which we believe isn't best practice but is what is defined within the specification).

n3rgy are considering the best approach to improve this situation, in the mean time please update your code to detect and correct these values appropriately.

**Comment by dmahen-admin** [comment]
@matroderick We're also seeing these numbers: 8590.017, 8590.041, 34364.271, 4295.103, 4295.084, 8590.119, 8590.063, 8591.484, 8590.421 which seem like errors. Have they also been noted?

**Comment by matroderick** [comment]
> I've also encountered a value of `38655.37` which also looks like an error code. We've previously also been told to remove `186227.0865`. Does anyone know which bit of the SMETs specification documents these? I've been struggling to find it.

The 0xFFFFFFFF (I think that's the right number of F's) are part of the SMETS standard but it seems individual meter manufacturers hare making new error codes up. I suspect there's going to be more discovered overtime without hope for a centralised list (manufactures are under no obligation to share this information or any defects their meters may or may not have).

**Comment by matroderick** [comment]
https://support.n3rgy.com/ is our new home for the FAQ on n3rgy and smart metering.
