### ISSUE TITLE
Missing meter data

### ISSUE THREAD

**Issue by matroderick** [n3rgy/data#2]
SMETS2 meters occasionally fail to response to requests for data, all meter manufactures and models seem to be affected by this issue (some significantly more than others). In the event of missing data, the n3rgy service continues to retry and re-request the missing data until this the data held is completed. Observations have shown this can sometimes take days or even weeks in some scenarios. 

This issue has been escalated to meter manufactures, the Department of Business, Energy and Industrial Strategy (BEIS), Ofgem, Smart Energy Code Panel and DCC and we are working closely to assist in its resolution.

n3rgy will also continue to optimise our platform to compensate for the issues within the wider industry smart meter ecosystem.

**Comment by matroderick** [comment]
Significant work as been performed by both n3rgy, DCC and BEIS to investigate this issue. It looks to be a systemic problem within the DCC and/or meters which causes requests to consistently fail in a number of scenarios and occasionally fail in many other scenarios. We continue to apply pressure on both BEIS, DCC and the community of meter manufactures to prioritise a resolution.

**Comment by matroderick** [comment]
This continues to be an issue with the national network which has now spread to enrolled SMETS1 devices (likely due to the complex nature of their integration with the national network). We continue to enhance our system to get the best possible result while operating across an often unreliable and unpredictable network of meters.

**Comment by gloomytrousers** [comment]
Could this be the reason why I've been unable to ever get my electricity data, even though I can get my gas data fine? I first signed up in the consumer portal about a year ago, and have a script which polls the API weekly, but no joy. (I can't download it manually via the portal either.)

**Comment by matroderick** [comment]
Update: we have a new release being deployed shortly (summer 2022) which will  improve data collection further (working around more issues with meters). In the mean time if collection stops please repeat the consent process which will also force a refresh of your meter data.

**Comment by gloomytrousers** [comment]
Thanks for the update. Alas a repeat of the consent process (a few days ago) still does not make any data available for my electricity (gas is fine).
```
{
  "resource": "/electricity/consumption/1",
  "responseTimestamp": "2022-06-08T06:22:17.357Z"
  "start": "202205310000",
  "end": "202206072359",
  "granularity": "halfhour",
  "values": [],
  "availableCacheRange": {},
  "unit": "kWh"
}
```
Unless you have any other suggestions, I'll cross my fingers for the summer release.
