### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by harvybob** [n3rgy/data#6]
Hi,

Thanks for the hard work on creating and allowing access to the data!

I am a homeowner, and have given n3rgy access to my data for collection.

I would like to run a script to grab my data for me to then store it locally, but am confused on how to pass my MAC address for getting the data.
Can anyone give me a quick dummy's guide on using the scripts to connect to get the data?

**Comment by matroderick** [comment]
Hi @harvybob sorry for the delay, please take a look at https://github.com/n3rgy/consumer-data for examples on the consumer access interface. You need to signup as a consumer first (so we start downloading your data from the meter - https://data.n3rgy.com/consumer/sign-up). If you have any further questions you can find us on twitter/linkedin/facebook as @n3rgy.

**Comment by harvybob** [comment]
Thanks for the update - I was trying to use it as just a python script run on a Linux OS.

I am registered for the consumer access but am unable to setup the environment - specifically the cookies side of things to get the python script to make a successful connection to pull the data.

**Comment by matroderick** [comment]
The scripts available in consumer-data project are hosted [here](https://homebrew.n3rgy.com/consumer-data/), on a raspberry pi. Cookies are only used within the interaction between browser and webpage, the interaction between the python scripts and the API uses the Authorization HTTP header. You could override all the cookie issues by hardcoding your MAC into line 37 of script. e.g 
headers = {'Authorization': '012334456789ABCD'}

**Comment by harvybob** [comment]
Great! thanks for that - I will pull a fresh set of code and try that!

**Comment by harvybob** [comment]
Thanks for the guidance @matroderick  I've managed to get the python script to get the data - however i had to make the following change in n3rgy-data.py
```
#if handler['n3rgyAuthorization']:
#       (apiSrv,AUTH) = handler['n3rgyAuthorization'].split(':')
#       if (apiSrv == 'live'):
#               url = "https://consumer-api.data.n3rgy.com"
```
and
```
#apiurl = url + path_info + "?" + querystring
apiurl = url + path_info + querystring + "?"
```
Not sure if that is the case for everyone, but i had to comment out the handler, and change the order of apiurl

**Comment by matroderick** [comment]
That's a little strange, I can see why you needed to comment the cookie handler part (as you're now not using cookies) but you'll need to keep the url= uncommented (otherwise it will go to the sandbox). However, reordering the apiurl should break it! Drop me an email at mat@n3rgy.com so we can get into more details

**Comment by harvybob** [comment]
@matroderick ignore me - i got the path_info and querystring mixed up!

I did have to # out the if handler as that kept failing so skipped it.

**Comment by harvybob** [comment]
Thanks for the guidance, ive got a script working to pull the data and write it off to a local MYSQL database daily
