### ISSUE TITLE
API Questions

### ISSUE THREAD

**Issue by jonathanadams** [n3rgy/data#7]
First of all thank you for your hard work in creating a medium to allow access to smart meter data.

I would quite like to implement the consumer api as component within [Home Assistant](https://home-assistant.io).

I am in the process of building an asynchronous python client for accessing consumer n3rgy data but have a few questions if someone wouldn't mind answering them?

- Are there any plans or are you guys able to implement an endpoint which will provide the latest available gas and electricity consumption reading? Something like `https://consumer-api.data.n3rgy.com/electricity/consumption/latest`and an equivalent for gas. This would be useful in my use case to be able to poll this endpoint every 30 mins or so to obtain the latest reading.
- In light of my previous question. Are there any rate limits imposed upon the consumer-api endpoints (i.e x amount of requests per day/hour per IP address or per auth key)? If so what are these? This would be useful so I can design my client to be courteous of any limits imposed.
- What is the typical lag on the consumption data? For example my granularity is half-hour but how long after a half-hour period do you receive the data from the smart meter and it appearing in the API?

Thank you for your time and help. It is appreciated.

**Comment by harvybob** [comment]
Hi Jonathan,

Don't take this as 100% truth, but I believe the data is updated daily, not sure if it is that the meter sends all the data in a single window type setup though, There are some products which allow you to get the data half hourly - https://www.hildebrand.co.uk/our-products/ but ive not set up/used this.

**Comment by slash909uk** [comment]
Hello there! Similar to Jonathan above, I too am considering implementing a bridge between my smart home solution (in my case [domoticz](https://domoticz.com/) ) and my smart meter data. Any information on his questions would help move this forward for us both.

TIA
Stu

**Comment by matroderick** [comment]
Hi Guys,
sorry, the github issues list isnt monitor (it's a relatively status FAQ of sorts). Please email support@data.n3rgy.com

But to answer you questions
- The default API call (with not start or end date) provides yesterday's readings. It is not possible to collect data more frequently in large volumes over the national smart meter network. Our free consumer service collects the data from your smart meter once per day via the national smart meter network. The hildebrand solution mentioned requires the purchase and installation of dedicated hardware which connects via (domestic) broadband and therefore collects data more frequently via alternative means (broadband)
- no limitations however note my previous point that the data is only collected from the meter once per day
- upto 24hrs

**Comment by slash909uk** [comment]
Thanks Matthew 👍
In conclusion this service can provide only historical data, not live data. Good to know! There are alternatives to provide live data streams locally, not via the DCC network as mentioned above. Hildebrand and Geotogether solutions already exist here on GitHub 🙂 see here:
https://github.com/topics/geotogether
https://github.com/topics/hildebrand
