### ISSUE TITLE
Improve API key expiry/regeneration process

### ISSUE THREAD

**Issue by richplane** [n3rgy/data#8]
At the moment, API keys expire without warning and it takes manual intervention to regenerate new keys.

Three things that could be done:

- Enable key regeneration after expiry. 
- Automated email reminders ahead of key expiry
- And/or (if it's easier!) an endpoint that returns the validity of the current API key

In a sandbox account where there is no dependency on invoicing the key seems to work in perpetuity but disappears from the data.n3rgy.com account page after one year. There is then no ability to retrieve or regenerate it.

**Comment by matroderick** [comment]
Hi Guys,
sorry, the github issues list isnt monitor (it's a relatively status FAQ of sorts). Please email support@data.n3rgy.com

This is on our backlog and will be updated shortly, the validity of the API key is available (only) through the customer portal (note, not consumer portal). For the moment please email support to restore your API key (sandbox or live) if you fail to regenerate the key before it expires
