### ISSUE TITLE
Get tariff data response out of schema

### ISSUE THREAD

**Issue by richplane** [n3rgy/data#9]
Hi - when making a request for tariff data for a meter we're getting a response which does not conform to the schema, which makes  the Python API library fail with a ValueError.

This is the response (from Swagger):

![image](https://user-images.githubusercontent.com/1793287/127304261-7ac8184f-92b1-4a6c-99dc-5e1b0ce8b3b9.png)

You can see that it does not report an `end` element to the availableCacheRange, which violates the schema

![image](https://user-images.githubusercontent.com/1793287/127304410-0bdb5d5c-1844-4e93-8a5d-82a4972f3853.png)

and means that the Python API library crashes out when it tries to deserialise the response into Python objects:

![image](https://user-images.githubusercontent.com/1793287/127304685-3da6283c-b021-43b9-b2b7-de501388f841.png)

It looks to me like this needs to be a server side fix.

Thanks

**Comment by matroderick** [comment]
Hi Guys,
sorry, the github issues list isnt monitor (it's a relatively status FAQ of sorts). Please email support@data.n3rgy.com
@richplane could you email this issue in place if it's still valid?
